controllers:
    resource: '../src/Controller/'
    type: attribute
    prefix: /api

keycload_controller:
    resource: '../src/Infrastructure/Keycloak/Controller'
    type: attribute
    prefix: /api

# nelmio_api_doc:
#     path: /api/docs
#     controller: nelmio_api_doc.controller.swagger_ui

# config/routes.yaml
app.swagger:
    path: /api/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }